version: "3.5"
services:
    mysql:
        image: mysql:latest
        container_name: zeeplend-db
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          
        volumes:
            - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
            - ./db_data:/var/lib/mysql